name: Merged

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Increment version number
    if: github.event.pull_request.draft == false
    runs-on: macos-13
    permissions:
      contents: write
      
    steps:
      - name: Create GitHub release
        uses: Oliver-Binns/Versioning@main
        with:
          ACTION_TYPE: 'Release'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
