name: Merged

on:
  push:
    branches: [ main, feature/publish-releases ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Increment version number
    if: github.event.pull_request.draft == false
    runs-on: macos-13
    permissions:
      contents: write
      
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Determine release increment
        id: determine_version_number
        run: |
          swift build
        
          swift run --skip-build Run increment \
            --repository $GITHUB_REPOSITORY \
            --sha $GITHUB_SHA \
            --token ${{ secrets.GITHUB_TOKEN }}
